language: scala
sudo: false
dist: trusty

scala:
  - 2.12.4

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.nvm

before_cache:
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable

script:
  - sbt scalafmt::test test:scalafmt::test sbt:scalafmt::test
  - sbt "reload plugins" scalafmt::test sbt:scalafmt::test
  - sbt scalastyle test:scalastyle
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt scripted
